// Copyright (c) <2011-2012> Daniel Peterson
// This file is part of Mini3D <www.mini3d.org>
// It is distributed under the MIT Software License <www.mini3d.org/license.php>

// Hex codes from WinUser.h (VK_**)

#if defined(__linux__) && !defined(ANDROID) && !defined(__APPLE__)

static const unsigned int MINI3D_UNICODE_PRIVATE_AREA_OFFSET = 0xF0000;

enum UnicodeKeyId {
    UKID_NONE       = 0,

    UKID_LEFT       = 0xFF96 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_UP         = 0xFF97 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_RIGHT      = 0xFF98 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_DOWN       = 0xFF99 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,

    UKID_SHIFT      = 0xFFE1 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_CTRL       = 0xFFE3 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_ALT        = 0xFFE9 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,

    UKID_F1         = 0xFFBE + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F2         = 0xFFBF + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F3         = 0xFFC0 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F4         = 0xFFC1 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F5         = 0xFFC2 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F6         = 0xFFC3 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F7         = 0xFFC4 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F8         = 0xFFC5 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F9         = 0xFFC6 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F10        = 0xFFC7 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F11        = 0xFFC8 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F12        = 0xFFC9 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET
};

#endif
