// Copyright (c) <2011-2012> Daniel Peterson
// This file is part of Mini3D <www.mini3d.org>
// It is distributed under the MIT Software License <www.mini3d.org/license.php>

// Hex codes from WinUser.h (VK_**)

#ifdef __APPLE__
#import "TargetConditionals.h"
#endif

#if TARGET_OS_IPHONE


static const unsigned int MINI3D_UNICODE_PRIVATE_AREA_OFFSET = 0xF0000;

enum UnicodeKeyId {
    UKID_NONE       = 0,

    UKID_LEFT       = 0x25 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_UP         = 0x26 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_RIGHT      = 0x27 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_DOWN       = 0x28 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,

    UKID_SHIFT      = 0x10 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_CTRL       = 0x11 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_ALT        = 0x12 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,

    UKID_F1         = 0x70 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F2         = 0x71 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F3         = 0x72 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F4         = 0x73 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F5         = 0x74 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F6         = 0x75 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F7         = 0x76 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F8         = 0x77 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F9         = 0x78 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F10        = 0x79 + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F11        = 0x7A + MINI3D_UNICODE_PRIVATE_AREA_OFFSET,
    UKID_F12        = 0x7B + MINI3D_UNICODE_PRIVATE_AREA_OFFSET
};

#endif
